CREATE TABLE user (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(16) NOT NULL,
  password varchar(255) NOT NULL,
  nickname varchar(50),
  avatar_url varchar(255),
  user_type tinyint DEFAULT 1,
  email varchar(100),
  phone varchar(20),
  gender tinyint DEFAULT 1,
  status tinyint DEFAULT 1,
  last_login_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  eye_care_mode tinyint DEFAULT 0,
  surprise_mode tinyint DEFAULT 0,
  CONSTRAINT uk_user_username UNIQUE (username)
);

CREATE TABLE job_category (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL,
  level tinyint NOT NULL,
  parent_id bigint,
  sort_order int DEFAULT 0,
  status tinyint DEFAULT 1,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint NOT NULL,
  name varchar(100) NOT NULL,
  description clob,
  requirements clob,
  status tinyint DEFAULT 1,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_job_category FOREIGN KEY (category_id) REFERENCES job_category (id)
);

CREATE TABLE ai_assessment_session (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_session_id varchar(64) NOT NULL,
  user_id bigint NOT NULL,
  job_id bigint NOT NULL,
  status varchar(32) NOT NULL,
  current_stage varchar(32) NOT NULL,
  elimination_reason varchar(255),
  final_summary clob,
  final_suggestion clob,
  start_time timestamp,
  end_time timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_assessment_session_id UNIQUE (assessment_session_id),
  CONSTRAINT fk_ai_assessment_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_assessment_job FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE
);

CREATE TABLE ai_resume_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_session_id varchar(64),
  user_id bigint NOT NULL,
  job_id bigint NOT NULL,
  file_name varchar(255) NOT NULL,
  file_size int NOT NULL,
  file_type varchar(20) NOT NULL,
  upload_time timestamp DEFAULT CURRENT_TIMESTAMP,
  overall_score tinyint,
  ai_analysis clob,
  ai_suggestions clob,
  CONSTRAINT fk_ai_resume_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_resume_job FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE
);

CREATE TABLE ai_question_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_session_id varchar(64),
  user_id bigint NOT NULL,
  job_id bigint NOT NULL,
  start_time timestamp,
  end_time timestamp,
  total_time int,
  overall_score tinyint,
  ai_suggestions clob,
  CONSTRAINT fk_ai_question_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_question_job FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE
);

CREATE TABLE ai_interview_round_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_session_id varchar(64),
  round_type varchar(32),
  user_id bigint NOT NULL,
  job_id bigint NOT NULL,
  start_time timestamp,
  end_time timestamp,
  total_time int,
  overall_score tinyint,
  ai_assessment clob,
  CONSTRAINT fk_ai_round_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_round_job FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE
);

CREATE TABLE agent_conversation_session (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  agent_key varchar(64) NOT NULL,
  chat_id varchar(80) NOT NULL,
  title varchar(255),
  preview varchar(500),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_chat UNIQUE (user_id, chat_id),
  CONSTRAINT uk_chat_id UNIQUE (chat_id)
);

CREATE TABLE agent_conversation_message (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id varchar(80) NOT NULL,
  turn_no int,
  role varchar(16) NOT NULL,
  content clob NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_agent_message_chat FOREIGN KEY (chat_id) REFERENCES agent_conversation_session (chat_id) ON DELETE CASCADE
);

CREATE TABLE agent_conversation_event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id varchar(80) NOT NULL,
  turn_no int,
  event_type varchar(64) NOT NULL,
  payload_json clob,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_agent_event_chat FOREIGN KEY (chat_id) REFERENCES agent_conversation_session (chat_id) ON DELETE CASCADE
);

CREATE TABLE agent_conversation_memory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chat_id varchar(80) NOT NULL,
  summary_hash varchar(64),
  summary_content clob,
  recent_turns_json clob,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_memory_chat_id UNIQUE (chat_id),
  CONSTRAINT fk_agent_memory_chat FOREIGN KEY (chat_id) REFERENCES agent_conversation_session (chat_id) ON DELETE CASCADE
);

CREATE TABLE feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  type varchar(20) NOT NULL,
  title varchar(100) NOT NULL,
  content clob NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'PENDING',
  reply clob,
  reply_time timestamp,
  admin_id bigint,
  admin_name varchar(100),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_user FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE blessing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  content clob NOT NULL,
  type varchar(50),
  status varchar(20) NOT NULL DEFAULT 'ACTIVE',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO job_category (id, name, level, parent_id, sort_order, status) VALUES
(101,'人工智能',2,NULL,101,1),(102,'机器学习',2,NULL,102,1),(103,'自然语言处理',2,NULL,103,1),(104,'智能算法',2,NULL,104,1),
(201,'大数据开发',2,NULL,201,1),(202,'数据分析',2,NULL,202,1),(203,'数据架构',2,NULL,203,1),(204,'数据治理',2,NULL,204,1),
(301,'嵌入式开发',2,NULL,301,1),(302,'物联网架构',2,NULL,302,1),(303,'传感器开发',2,NULL,303,1),(304,'物联网安全',2,NULL,304,1),
(401,'系统架构',2,NULL,401,1),(402,'智能运维',2,NULL,402,1),(403,'自动化测试',2,NULL,403,1),(404,'智能产品',2,NULL,404,1);

INSERT INTO job (id, category_id, name, description, requirements, status) VALUES
(1,101,'人工智能工程师','负责将机器学习、大模型与智能系统能力落地到真实业务场景。','熟悉 Python、机器学习框架、大模型应用、RAG 和模型评测。',1),
(2,102,'机器学习工程师','负责特征工程、模型训练、效果评估和算法服务化。','熟悉机器学习算法、实验方法、数据分析和工程实现。',1),
(3,103,'自然语言处理工程师','负责文本理解、对话系统、信息抽取和大模型应用。','熟悉 NLP 基础任务、Transformer、大模型应用或微调。',1),
(4,201,'大数据开发工程师','负责离线数仓、实时计算和数据链路建设。','熟悉 Spark、Flink、Hive、Kafka、数仓建模和数据质量。',1),
(5,202,'数据分析师','负责业务分析、指标体系、实验评估和数据洞察。','熟练掌握 SQL、统计分析、业务拆解和可视化工具。',1),
(6,203,'数据架构师','负责企业数据架构、数据模型和数据平台演进规划。','熟悉分布式计算、湖仓一体、数据治理和数据服务。',1),
(7,301,'嵌入式软件工程师','负责智能硬件和物联网设备的软件开发。','熟悉 C/C++、Linux/RTOS、驱动开发和通信协议。',1),
(8,302,'物联网架构师','负责设备接入、消息通信、规则引擎和边缘协同架构。','熟悉 MQTT、CoAP、WebSocket、TCP/IP 和高可用架构。',1),
(9,304,'物联网安全专家','负责设备、通信链路、云平台和数据安全体系建设。','熟悉网络安全、系统安全、固件分析和物联网协议安全。',1),
(10,401,'系统架构师','负责大型业务系统和技术中台的整体架构设计。','熟悉微服务、缓存、消息队列、数据库和高可用架构。',1),
(11,402,'智能运维工程师','负责监控告警、自动化发布、故障自愈和 AIOps 能力。','熟悉 Linux、Kubernetes、Prometheus、日志链路和自动化开发。',1),
(12,403,'自动化测试工程师','负责质量保障体系和自动化测试平台建设。','熟悉接口测试、UI 自动化、性能测试、Mock 和 CI/CD。',1),
(13,404,'智能产品经理','负责 AI 产品规划、设计、指标体系和商业化落地。','理解大模型、推荐、搜索、智能对话和产品实验方法。',1),
(14,303,'传感器开发工程师','负责传感器选型、驱动适配、信号处理和可靠性验证。','熟悉传感器原理、接口协议、硬件调试和数据处理。',1),
(15,204,'数据治理专家','负责数据标准、质量、元数据、主数据和数据安全治理。','熟悉 DAMA、数据标准、数据质量、血缘分析和权限管理。',1),
(16,104,'智能算法工程师','负责预测、推荐、排序、优化和智能决策算法落地。','熟悉机器学习、优化算法、概率统计和主流算法框架。',1);
